### ISSUE TITLE
Dataset Access

### ISSUE THREAD

**Issue by park-youngjae** [Zjut-MultimediaPlus/MGTCF#1]
Thank you for your wonderful work.

I would like to implement your code.

Can you share your data?

Thank you.

**Comment by xiaochengfuhuo** [comment]
Thanks for your interest in my work.
I have released the data on https://pan.baidu.com/s/1qLEVymQ3ivvqAbgGBNkgaQ?pwd=rgwn.

**Comment by park-youngjae** [comment]
Thank you for caring. However, I am located outside mainland China and have difficulty accessing Baidu. Is it possible for you to upload the data to Google Cloud or OneDrive?

**Comment by xiaochengfuhuo** [comment]
Thanks for your advice. I uploaded it to  Google Cloud  -- https://drive.google.com/file/d/1AZhiGk-cTvcMdL9jerL25KmTzqD8Kab-/view?usp=sharing

**Comment by park-youngjae** [comment]
Thanks! it works!

**Comment by park-youngjae** [comment]
Thanks! it works!!
