### ISSUE TITLE
关于实验结果的一些问题

### ISSUE THREAD

**Issue by Samhoo926** [Zjut-MultimediaPlus/MGTCF#3]
本人按照说明文档中的步骤，将数据集放入相应的文件夹中，在3090的环境下进行实验，实测代码有效。最终在2019年测试集上的结果如下：
![D5{Y`(1RRKE9HB4{WTE19G7](https://github.com/Zjut-MultimediaPlus/MGTCF/assets/87103117/7e17951a-cec5-460c-a3a0-40e7e0b7d52d)
此结果与原文中的结果不一致。想咨询一下作者还有哪些需要调的参数或者注意事项，感谢帮助！！！

**Comment by xiaochengfuhuo** [comment]
论文中的结果是2017-2019三年数据测试的结果。你把evaluate_model_Me 文件中的  第22行  test2019 改成test 测试一下。
至于模型给出的结果和论文的不一样--因为在解码过程中会加入高斯噪声进行使得模型进行多趋势的预测，所以不同机子测试效果可能会不太一样。但是相差不多。

训练结果的话  我训练的时候也没有固定随机种子，结果可能也会有点偏差

你先把第22行  test2019 改成test 测试一下看看
我的测试环境是  A6000
