### ISSUE TITLE
多GPU训练模型

### ISSUE THREAD

**Issue by Samhoo926** [Zjut-MultimediaPlus/MGTCF#4]
想要咨询一下作者，如果使用多个GPU训练该模型，需要在哪些地方修改代码，感谢帮助！！！
PS:单个GPU训练模型时间太久了，测试改进后的模型性能需要花费太多时间，效率很低！

**Comment by xiaochengfuhuo** [comment]
目前 GAN模型 不太好用多GPU, 你可能需要查查  怎么用多GPU训练GAN模型

**Comment by Samhoo926** [comment]
回复已收到！在train.py文件中还发现代码里的超参数与原文中存在不一致的情况(batch_size与pi_pre_epoch)，想请教一下作者，该遵循哪种？

**Comment by xiaochengfuhuo** [comment]
batch_size是我在自己机子上测试  改小了   用96吧    pi_pre_epoch用5吧   这些也需要自己测试  哪个更好一些

**Comment by Samhoo926** [comment]
下图中绿色圈出的部分为1D数据与2D数据的融合步骤，文中直接将处理后2种模态数据进行相加，想咨询下作者，在设计模型的过程，有没有试验过其他融合方法？
![QQ截图20230720195218](https://github.com/Zjut-MultimediaPlus/MGTCF/assets/87103117/2950a3e9-d081-4091-9c98-1242dbd587db)

**Comment by xiaochengfuhuo** [comment]
对这个地方的特征融合方式，我当时好像没有做过多的思考，没有用过其他方法  比如说cat或者两种向量进行加权 啥的

**Comment by Samhoo926** [comment]
回复已收到，再次感谢！
